" Picking & setting a runtimepath for vim (this will set ~/.vim dir as rtp)
" runtimepath is the list of files/folders vim will look for config settings
let $RTP=split(&runtimepath, ',')[0]

" Setting vimrc file path
let $RC="$HOME/.vim/vimrc"

set t_Co=256              " Enable 256 color support
set nocompatible          " Disable old vi compatibility

" filetype - will try to recognize type of file and set 'filetype' option
" plugin   - to load plugins for specific file type
" indent   - to load indentation rules for specific file type
" syntax   - to enable syntax highlighting(colouring) specific to file type
filetype plugin indent on
syntax on

" NOTE: File type specific formating rules are specified in
" ~/.vim/after/ftplugin/*.vim location. These will added over the
" pre-defined rules


" -----------------------
" VIM-PLUGIN LIST
" -----------------------
" PlugInstall or PlugUpdate - to update/install plugin
" PlugUpgrade               - to update vim-plug
call plug#begin()

" Colorschemes
Plug 'sainnhe/everforest'     " Everforest - green based colorscheme
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'cocopon/iceberg.vim'
Plug 'arcticicestudio/nord-vim'
Plug 'scheakur/vim-scheakur'
Plug 'Badacadabra/vim-archery'
Plug 'gruvbox-community/gruvbox'


Plug 'preservim/nerdtree'       " NerdTree install
Plug 'jiangmiao/auto-pairs'     " Insert/delete brackets, parens, quotes in pair

call plug#end()


" -----------------------------
" NERD-TREE CONFIGURATIONS
" -----------------------------
let NERDTreeShowBookmarks = 1   " Show the bookmarks table
let NERDTreeShowHidden = 1      " Show hidden files
let NERDTreeShowLineNumbers = 0 " Hide line numbers
let NERDTreeMinimalMenu = 1     " Use the minimal menu (m)
let NERDTreeWinPos = 'left'     " Panel opens on the left side
let NERDTreeWinSize = 27        " Set panel width to 31 columns

" Start NERDTree whenever vim openes and leave the cursor in it.
" autocmd VimEnter * NERDTree

" Start NERDTree and put the cursor back in the other window.
" autocmd VimEnter * NERDTree | wincmd p

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" Close the tab if NERDTree is the only window remaining in it.
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif


" -------------------------------
" VIM GENERAL CONFIGURATIONS
" -------------------------------
colorscheme nord
set background=dark       " Setting colorscheme mode

" Make the background transparent
" highlight Normal guibg=NONE ctermbg=NONE

set cursorline            " Highlight current line
set number                " Show line numbers
set numberwidth=1         " Set line number width (default is 4)
set mouse=a               " Mouse drag/resize the split windows

set ignorecase            " Ignore case while searching
set hlsearch              " Highlight matched keyword in the search
set incsearch             " Show partial match while searching
set smartcase             " use case if any caps used

set scrolloff=8           " Set min number of lines to keep up while scrolling

" To fix not-working backspace key in insert mode
set backspace=indent,eol,start

" Fix error thrown while opening new file and changes in the current
" file has not yet saved
set hidden

" Setting a common dir to hold all swap files
" 'directory' option contains list of path which vim tries to save swap
" ^= shorthand for :set
" // use absolute path while creating swap files to avoid collisions
set directory^=$HOME/.vim/swap// 

" expandtab  - enter spaces when TAB is pressed
" tabstop    - column size to represent TAB
" shiftwidth - no of spaces to use for indentation
" autoindent - copy indent from curent line when starting new line
" smartindent- works for c files, smarter version of autointent
"            - dont use it when using file type based indentation
" softtabstop- when hitting backspace define how many spaces to delete
"
" To turn off any options enabled by set keyword, just prefix the parameter 
" with "no" EX: set nonumber, set noignorecase


" ---------------------------------
" SETTING CODE FOLDING OPTIONS
" ---------------------------------
" Automatically save the created folding
autocmd BufWinLeave *.* mkview
" Automatically load saved folds if it exists
autocmd BufWinEnter *.* silent loadview


" --------------------------
" ALTERNATE KEY MAPPING
" --------------------------
" Paste mode - used to turn of the autoindent feature to prevent
" unnecessary indentation while pasting code into vi
set pastetoggle=<F2>

" Remapping scrolling one line at a time
" Rather than pressing CTRL-E to scroll use CTRL-J
nnoremap <C-J> <C-E>
nnoremap <C-K> <C-Y>

" Remapping movement keys b/w splits in vim
" Rather than presing CTRL-W L now press CTRL-L
" nnoremap <C-J> <C-W>j
" nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-H> <C-W>h

" Open/Close Nerd tree CTRL-n
nmap <C-n> :NERDTreeToggle<CR>
